- name: Sync All DEX Repositories to Local Workspace
  hosts: local
  connection: local
  become: false # Chạy với user thường ở local, không dùng sudo
  gather_facts: false

  roles:
    - workspace
