---
workspace_dir: "{{ playbook_dir }}/../../.."
github_org: "git@github.com:dex-hq-p"

dex_repositories:
  - dex-gitops
  - dex-terraform
  - dex-helm

# ─── Override for local environment ───────────────────────────────────────────

# PostgreSQL
postgresql_version: "16"
postgresql_port: "5432"
postgresql_data_dir: "{{ playbook_dir }}/../../../volumes/postgresql/data"
postgresql_db: "keycloak"
postgresql_user: "keycloak"
postgresql_password: "keycloak_local_pass"

# Keycloak
keycloak_version: "24.0.5"
keycloak_port: "8080"
keycloak_admin_user: "admin"
keycloak_admin_password: "admin"
